name: Build & Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: ./.github/workflows/setup.yml

      - name: Build
        run: |
          npm run bundle
          npm run bundle-min

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./packages/**/build

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: ./.github/workflows/setup.yml

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        run: ls -R

      - name: Test
        uses: ./.github/workflows/test.yml

